from sqlalchemy import Column, Integer, String, Float, DateTime, Text
from sqlalchemy.sql import func
from database import Base

class ProductTag(Base):
    """
    This table stores every product that gets tagged by AI
    """
    __tablename__ = "product_tags"

    id = Column(Integer, primary_key=True, index=True)
    
    # Product info (what user sends)
    product_name = Column(String(255), nullable=False)
    product_description = Column(Text, nullable=False)
    
    # AI generated output
    category = Column(String(100))
    sub_category = Column(String(100))
    seo_tags = Column(Text)               # stored as comma-separated string
    sustainability_filters = Column(Text) # stored as comma-separated string
    confidence_score = Column(Float)
    
    # Logging
    ai_prompt_used = Column(Text)         # what prompt we sent to Gemini
    ai_raw_response = Column(Text)        # what Gemini returned (for debugging)
    
    # Timestamp
    created_at = Column(DateTime(timezone=True), server_default=func.now())


class AILog(Base):
    """
    Logs every AI call made — prompt sent + response received
    """
    __tablename__ = "ai_logs"

    id = Column(Integer, primary_key=True, index=True)
    module_name = Column(String(100))     # e.g. "module1_tagger"
    prompt_sent = Column(Text)
    response_received = Column(Text)
    success = Column(Integer, default=1)  # 1 = success, 0 = failed
    created_at = Column(DateTime(timezone=True), server_default=func.now())



class B2BProposal(Base):
    """
    Stores B2B bulk purchase proposals generated by AI for corporate clients
    """
    __tablename__ = "b2b_proposals"

    id = Column(Integer, primary_key=True, index=True)
    
    # Client information
    client_name = Column(String(255), nullable=False)
    industry = Column(String(100), nullable=False)
    budget = Column(Float, nullable=False)
    num_employees = Column(Integer, nullable=False)
    preferences = Column(Text)  # stored as comma-separated string
    
    # AI-generated proposal data
    recommended_products = Column(Text)  # stored as JSON string
    impact_summary = Column(Text)
    total_cost = Column(Float)
    budget_utilization_percent = Column(Float)
    impact_positioning = Column(Text)
    
    # Logging
    ai_prompt_used = Column(Text)
    ai_raw_response = Column(Text)
    
    # Timestamp
    created_at = Column(DateTime(timezone=True), server_default=func.now())


class ImpactReport(Base):
    """
    Stores environmental impact reports for customer orders
    """
    __tablename__ = "impact_reports"

    id = Column(Integer, primary_key=True, index=True)
    order_id = Column(Integer, nullable=False, index=True)
    product_names = Column(Text)  # stored as comma-separated string
    
    # Calculated metrics
    plastic_saved_grams = Column(Float)
    carbon_avoided_kg = Column(Float)
    local_sourcing_percent = Column(Float)
    
    # AI-generated impact statement
    impact_statement = Column(Text)
    
    # Logging
    ai_prompt_used = Column(Text)
    ai_raw_response = Column(Text)
    
    # Timestamp
    created_at = Column(DateTime(timezone=True), server_default=func.now())


class Order(Base):
    """
    Stores customer orders for WhatsApp bot order status queries
    """
    __tablename__ = "orders"

    id = Column(Integer, primary_key=True, index=True)
    order_number = Column(String(50), unique=True, nullable=False, index=True)
    customer_name = Column(String(255), nullable=False)
    customer_phone = Column(String(20), nullable=False, index=True)
    status = Column(String(50), nullable=False)  # "pending", "shipped", "delivered"
    total_amount = Column(Float, nullable=False)
    product_name = Column(String(255))
    quantity = Column(Integer)
    
    # Timestamp
    created_at = Column(DateTime(timezone=True), server_default=func.now())


class WhatsAppLog(Base):
    """
    Logs all WhatsApp conversations for customer service tracking
    """
    __tablename__ = "whatsapp_logs"

    id = Column(Integer, primary_key=True, index=True)
    customer_phone = Column(String(20), nullable=False, index=True)
    message_received = Column(Text, nullable=False)
    intent_detected = Column(String(50))
    response_sent = Column(Text)
    
    # Timestamp
    created_at = Column(DateTime(timezone=True), server_default=func.now())


class EscalationLog(Base):
    """
    Logs customer issues that require human intervention
    """
    __tablename__ = "escalation_logs"

    id = Column(Integer, primary_key=True, index=True)
    customer_phone = Column(String(20), nullable=False, index=True)
    issue_description = Column(Text, nullable=False)
    status = Column(String(50), default="pending")  # "pending", "resolved", "closed"
    
    # Timestamp
    created_at = Column(DateTime(timezone=True), server_default=func.now())
